services:
  postgres:
    image: postgres:16
    container_name: linkping_db
    restart: always
    environment:
      POSTGRES_DB: linkping
      POSTGRES_USER: yashaswi
      POSTGRES_PASSWORD: secret
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: linkping_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pg_data: